name: Deploy to Test Server
on:
  push:
    branches:
      - prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and Push
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/home-page
          docker build \
            --build-arg VITE_AUTH_ENDPOINT=${{ secrets.VITE_AUTH_ENDPOINT }} \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
            --build-arg VITE_INSTAGRAM_LINK=${{ secrets.VITE_INSTAGRAM_LINK }} \
            --build-arg VITE_FACEBOOK_LINK=${{ secrets.VITE_FACEBOOK_LINK }} \
            --build-arg VITE_TIKTOK_LINK=${{ secrets.VITE_TIKTOK_LINK }} \
            --build-arg VITE_X_LINK=${{ secrets.VITE_X_LINK }} \
            --build-arg VITE_LINKEDIN_LINK=${{ secrets.VITE_LINKEDIN_LINK }} \
            --build-arg VITE_INTERCOM_APP_ID=${{ secrets.VITE_INTERCOM_APP_ID }} \
            -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Trigger Infra Deployment
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GHCR_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Havesta-Logistics-Limited/havesta-infra-main/dispatches \
          -d '{"event_type": "deploy-test-service", "client_payload": {"services": "home-page", "image_tag": "${{ github.sha }}"}}'