name: Build & Push to GHCR.

on:
  push:
    branches:
      - prod   

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/home-page
          docker build \
            --build-arg VITE_AUTH_ENDPOINT=${{ secrets.VITE_AUTH_ENDPOINT }} \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
            --build-arg VITE_INSTAGRAM_LINK=${{ secrets.VITE_INSTAGRAM_LINK }} \
            --build-arg VITE_FACEBOOK_LINK=${{ secrets.VITE_FACEBOOK_LINK }} \
            --build-arg VITE_TIKTOK_LINK=${{ secrets.VITE_TIKTOK_LINK }} \
            --build-arg VITE_X_LINK=${{ secrets.VITE_X_LINK }} \
            --build-arg VITE_LINKEDIN_LINK=${{ secrets.VITE_LINKEDIN_LINK }} \
            --build-arg VITE_INTERCOM_APP_ID=${{ secrets.VITE_INTERCOM_APP_ID }} \
            -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/home-page
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
